### ISSUE TITLE
[Feature Request] Version updating

### ISSUE THREAD

**Issue by Alfredoes234** [AMythicDev/zigverm#1]
I do not know if this is how you want this project to work. But a way to update from the latest installed version would be nice and if there already is a way, a prompt instruction on the READ-ME would be helpful for clarity and documentation.

**Comment by AMythicDev** [comment]
> But a way to update from the latest installed version

Can you elaborate on whose's version. If you are talking about updating Zig's version, I have mentioned the command in the CLI help and if you are asking for updating `zigverm` itself then it's the thing that I am working on right now. I can't find a cross-platform library to handle .zip files for Zig hence it's taking me some time.

**Comment by Alfredoes234** [comment]
Sorry then, I meant updating zig. It's just not really that clear on the readme as it does not really indicate that there's a CLI tool/no basic usage examples. So I thought you had not implemented it yet.

**Comment by AMythicDev** [comment]
Ah cool, I will add a few usage examples in the README today or tomorrow.

Thanks for letting me know.

**Comment by AMythicDev** [comment]
I have added a [quick guide](/AMythicDev/zigverm/blob/main/docs/quick-guide.md), its not that detailed but I will continue to add further docs as zigverm matures.
